package com.classmate.note.dto.message;

public enum SessionNoteRealtimeEventType {
	DOCUMENT_BLOCK_EDITING_STARTED,
	DOCUMENT_BLOCK_EDITING_HEARTBEAT,
	DOCUMENT_BLOCK_EDITING_STOPPED,
	DOCUMENT_BLOCK_DRAFT_CHANGED,
	DOCUMENT_BLOCK_SAVED,
	DOCUMENT_BLOCK_CREATED,
	DOCUMENT_BLOCK_DELETED,
	DOCUMENT_BLOCK_CONFLICT,
	DOCUMENT_RESYNC_REQUIRED
}
